[metadata]
name = "dfint localization hook offsets"
version = "51.01-beta20 steam win64"
checksum = 0x66BC7F04

[offsets]
string_copy_n = 0x1C580
string_append_n = 0x1C6C0
std_string_ctor = 0x29AA0
addst = 0x98D160
addst_top = 0x98D240
addst_flag = 0x98D070
standardstringentry = 0xA9C070
simplify_string = 0x457310
upper_case_string = 0x457650
lower_case_string = 0x4574B0
capitalize_string_words = 0x4577F0
capitalize_string_first_word = 0x457A70