[metadata]
name = "dfint localization hook offsets"
version = "51.01-beta21 steam win64"
checksum = 0x66CF1D91

[offsets]
string_copy_n = 0x1E0E0
string_append_n = 0x1E220
std_string_ctor = 0x2B600
addst = 0x9A2260
addst_top = 0x9A2340
addst_flag = 0x9A2170
standardstringentry = 0xAB1170
simplify_string = 0x467430
upper_case_string = 0x467770
lower_case_string = 0x4675D0
capitalize_string_words = 0x467910
capitalize_string_first_word = 0x467B90