[metadata]
name = "dfint localization hook offsets"
version = "51.01-beta18 steam win64"
checksum = 0x667A3ABA

[offsets]
string_copy_n = 0x1C580
string_append_n = 0x1C6C0
std_string_ctor = 0x29AA0
addst = 0x97B7E0
addst_top = 0x97B8C0
addst_flag = 0x97B6F0
standardstringentry = 0xA89E90
simplify_string = 0x44A650
upper_case_string = 0x44A990
lower_case_string = 0x44A7F0
capitalize_string_words = 0x44AB30
capitalize_string_first_word = 0x44ADB0
