[metadata]
name = "dfint localization hook offsets"
version = "51.01-beta22 steam win64"
checksum = 0x66D8442C

[offsets]
string_copy_n = 0x1F820
string_append_n = 0x1F960
std_string_ctor = 0x2CC80
addst = 0x9EAA80
addst_top = 0x9EAB60
addst_flag = 0x9EA990
standardstringentry = 0xAFE8E0
simplify_string = 0x49E3F0
upper_case_string = 0x49E730
lower_case_string = 0x49E590
capitalize_string_words = 0x49E8D0
capitalize_string_first_word = 0x49EB60