[metadata]
name = "dfint localization hook offsets"
version = "51.01-beta14 steam win64"
checksum = 0x6641FA3F

[offsets]
string_copy_n = 0x1C570
string_append_n = 0x1C6B0
std_string_ctor = 0x29A80
addst = 0x96B100
addst_top = 0x96B1E0
addst_flag = 0x96B010
standardstringentry = 0xA791F0
simplify_string = 0x4451D0
upper_case_string = 0x445510
lower_case_string = 0x445370
capitalize_string_words = 0x4456B0
capitalize_string_first_word = 0x445930
