[metadata]
name = "dfint localization hook offsets"
version = "51.01-beta12 steam win64"
checksum = 0x6620E355

[offsets]
string_copy_n = 0x1C570
string_append_n = 0x1C6B0
std_string_ctor = 0x29A70
addst = 0x95D260
addst_top = 0x95D340
addst_flag = 0x95D170
standardstringentry = 0xA6B340
simplify_string = 0x437FB0
upper_case_string = 0x4382F0
lower_case_string = 0x438150
capitalize_string_words = 0x438490
capitalize_string_first_word = 0x438710
