name: Update dictionary manifest
on:
  repository_dispatch:
    types: [dict]

jobs:
  dict:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run update script
        run: python3 ./automation/dict_manifest_update.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Update dictionary manifest"
